
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork


  etl:
    restart: always
    build:
      context: ./etl
    depends_on:
      - postgres
    networks:
      - mynetwork

  nest-api:
    restart: always
    build:
      context: ./nest-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


volumes:
  pgdata: